# Generated by Django 4.2.7 on 2025-07-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='category',
            field=models.CharField(blank=True, choices=[('ones', 'Ones'), ('twos', 'Twos'), ('threes', 'Threes'), ('fours', 'Fours'), ('fives', 'Fives'), ('sixes', 'Sixes'), ('three_of_a_kind', 'Three of a Kind'), ('four_of_a_kind', 'Four of a Kind'), ('full_house', 'Full House'), ('small_straight', 'Small Straight'), ('large_straight', 'Large Straight'), ('yahtzee', 'Yahtzee'), ('chance', 'Chance')], max_length=20, null=True),
        ),
    ]
