# Generated by Django 4.2.7 on 2025-07-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_score_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('player', 'room', 'round_number', 'category')},
        ),
    ]
