# Generated by Django 5.1.4 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_score_category_non_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="game_type",
            field=models.CharField(
                choices=[("yahtzee", "Yahtzee"), ("tally", "Generic Tally")],
                max_length=20,
            ),
        ),
    ]
